classDiagram

class Room{
    -long id
    -String description
    -int capacity
}

class Session{
    -long id
    -DateTime datetime
    -Room room
    -LinkedList participants

    -registerParticipant(Participante part)
}

class RegisterCard{
    -long id
}

class Participant{
    -long id
    -int avaliacao
    -String nome
    -String cpf

    - Card createCard()
}

class Speaker{
    -long id
    -String nome
    -String cpf

    - Card createCard()
}

class Subscription{
    -long id
    -Participant participant
    -Session session
    -Feedback feedback
}

class Event{
    -long id
    -Date date
}

class Feedback{
    -long id
    -int finalCapacity
    -int predictedCapacity
    -double rating
}

%% Heranças


Subscription "0.*" --o "1.1" Participant
Subscription "1.*" --o "1.1" Session

Session "1.1" *-- "1.*" Speaker

Room "1.1" --* "0.1" Session
Session "1.*" --* "1.1" Event

Session "1.1" o-- "1.1" Feedback